// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use process.env directly to allow prisma generate to work without DATABASE_URL
    // (needed for Vercel builds where env vars aren't available during npm install)
    url: process.env.DATABASE_URL ?? "",
  },
});
